### ISSUE TITLE
Opening suggestion

### ISSUE THREAD

**Issue by tomosullivan8** [dahlia-os/armadillo#2]
Is there an issue with opening a suggestion and the mapping to a specific story?

I fixed the issue with the rendering box that occured on opening a suggestion originally but now the suggestion doesn't map to a specific story_id correctly and just disappears - but acts as if the story has been opened.

**Comment by tomosullivan8** [comment]
Fixed this issue. The onSuggestionExpanded and onSuggestionSplashed weren't included to open the relevant stories.

**Comment by Horus125** [comment]
Sorry for the late reply, could you make a pull request with your fixes?
